config/routes.rb
Rails.application.routes.draw do
  resources :whos do
    collection { post :import_csv_data }
  end
  get 'who_starter_btn' => 'whos#who_starter_btn'
  get 'who/import_page' => 'whos#import_page'
  get 'who/search' => 'whos#search'
  get 'who_power_btn' => 'whos#who_power_btn'
  
  resources :indexer_terms do
    collection { post :import_csv_data }
  end
  get 'indexer_term/import_page' => 'indexer_terms#import_page'

  resources :indexers do
    collection {post :import_csv_data}
    #   get :merge_data, on: :collection
  end
  get 'indexer/search' => 'indexers#search'
  get 'indexer/import_page' => 'indexers#import_page'
  get 'page_finder_btn' => 'indexers#page_finder_btn'
  get 'reset_errors_btn' => 'indexers#reset_errors_btn'
  get 'indexer_power_btn' => 'indexers#indexer_power_btn'
  get 'template_finder_btn' => 'indexers#template_finder_btn'
  get 'rooftop_data_getter_btn' => 'indexers#rooftop_data_getter_btn'
  get 'meta_scraper_btn' => 'indexers#meta_scraper_btn'
  get 'indexer/show_detail' => 'indexers#show_detail'
  get 'url_redirect_checker_btn' => 'indexers#url_redirect_checker_btn'
  get 'score_calculator_btn' => 'indexers#score_calculator_btn'
  get 'scraper_migrator_btn' => 'indexers#scraper_migrator_btn'

  get 'migrate_address_to_staffers_btn' => 'indexers#migrate_address_to_staffers_btn'

  get 'id_sorter_btn' => 'indexers#id_sorter_btn'
  get 'finalizer_btn' => 'indexers#finalizer_btn'
  get 'phone_formatter_finalizer_btn' => 'indexers#phone_formatter_finalizer_btn'
  get 'geo_to_indexer_btn' => 'indexers#geo_to_indexer_btn'
  get 'address_formatter_btn' => 'indexers#address_formatter_btn'
  get 'phone_migrator_btn' => 'indexers#phone_migrator_btn'


  resources :locations do
    collection {post :import_csv_data}
    get :merge_data, on: :collection
    get :flag_data, on: :collection
  end
  get 'location/import_page' => 'locations#import_page'
  get 'location/search' => 'locations#search'
  get 'geo_places_starter_btn' => 'locations#geo_places_starter_btn'
  get 'location_power_btn' => 'locations#location_power_btn'
  get 'turbo_matcher_btn' => 'locations#turbo_matcher_btn'
  get 'location_cleaner_btn' => 'locations#location_cleaner_btn'
  get 'geo_update_migrate_btn' => 'locations#geo_update_migrate_btn'
  # get 'geo_starter_btn' => 'locations#geo_starter_btn'

  resources :staffers do
    collection { post :import_csv_data }
  end
  get 'staffer/import_page' => 'staffers#import_page'
  get 'staffer/search' => 'staffers#search'
  get 'staffer/acct_contacts' => 'staffers#acct_contacts'
  get 'cs_data_getter_btn' => 'staffers#cs_data_getter_btn'
  get 'staffer_sfdc_id_cleaner_btn' => 'staffers#staffer_sfdc_id_cleaner_btn'
  get 'staffer_power_btn' => 'staffers#staffer_power_btn'
  get 'crm_staff_counter_btn' => 'staffers#crm_staff_counter_btn'

  resources :cores do
    collection { post :import_core_data }
    get :merge_data, on: :collection
    get :flag_data, on: :collection
    get :drop_data, on: :collection
  end
  get 'core/import_page' => 'cores#import_page'
  get 'core/search' => 'cores#search'
  # # Clean Data Buttons
  # get 'core_comp_cleaner_btn' => 'cores#core_comp_cleaner_btn'
  get 'core_power_btn' => 'cores#core_power_btn'
  get 'col_splitter_btn' => 'cores#col_splitter_btn'

  resources :in_host_pos do
    collection { post :import_csv_data }
  end
  get 'in_host_po/import_page' => 'in_host_pos#import_page'

  resources :dashboards do
    collection { post :import_csv_data }
  end
  get 'dashboard/import_page' => 'dashboards#import_page'
  get 'dashboard_mega_btn' => 'dashboards#dashboard_mega_btn'
  get 'cores_dash_btn' => 'dashboards#cores_dash_btn'
  get 'delayed_jobs_dash_btn' => 'dashboards#delayed_jobs_dash_btn'
  get 'franchise_dash_btn' => 'dashboards#franchise_dash_btn'
  get 'indexer_dash_btn' => 'dashboards#indexer_dash_btn'
  get 'geo_locations_dash_btn' => 'dashboards#geo_locations_dash_btn'
  get 'staffers_dash_btn' => 'dashboards#staffers_dash_btn'
  get 'users_dash_btn' => 'dashboards#users_dash_btn'
  get 'whos_dash_btn' => 'dashboards#whos_dash_btn'
  get 'summarize_data' => 'dashboards#summarize_data'
  get 'dashboard_power_btn' => 'dashboards#dashboard_power_btn'


  devise_for :users

  #==== Delayed_Jobs_Interface Starts=========
  # match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # #==== Search Pages Start=========
  post 'search_result_page_core' => 'search#search_result_core'
  post 'search_result_page_staffer' => 'search#search_result_staffer'
  post 'search_result_page_location' => 'search#search_result_location'
  post 'search_result_page_indexer' => 'search#search_result_indexer'
  post 'search_result_page_indexer' => 'search#search_result_indexer'


  get 'admin/index'
  get 'admin/starters'
  get 'admin/change_user_level' => 'admin#change_user_level'
  get 'admin/delete_user' => 'admin#delete_user'
  get 'admin/developer' => 'admin#developer'

  root 'welcome#index'


  # Hide all CRUD actions 2017.03.10 ==================================

  # # === Google API Route ===
  # get '/search' => 'search#index'

  # resources :in_text_pos do
  #     collection { post :import_csv_data }
  # end
  # get 'in_text_po/import_page' => 'in_text_pos#import_page'
end

app/controllers/cores_controller.rb
class CoresController < ApplicationController
  before_action :intermediate_and_up, only: [:index, :show, :search]
  before_action :advanced_and_up, only: [:edit, :update, :merge_data, :flag_data, :drop_data]
  before_action :admin_only, only: [:new, :create, :destroy, :import_page, :import_core_data, :core_comp_cleaner_btn, :core_power_btn, :col_splitter_btn]
  before_action :set_core, only: [:show, :edit, :update, :destroy]
  before_action :set_core_service, only: [:index, :core_comp_cleaner_btn, :core_power_btn, :col_splitter_btn, :merge_data, :flag_data, :drop_data]
  before_action :set_option_list, only: [:index, :search]

  # GET /cores
  # GET /cores.json
  def index
    if choice_hash = get_selected_status_core
      clean_choice_hash = {}
      @view_mode = choice_hash[:view_mode]

      choice_hash.each do |key, value|
        clean_choice_hash[key] = value if !value.nil? && value != "" && key != :view_mode
      end
      @selected_data = Core.where(clean_choice_hash)
    else # choice_hash is nil
      @selected_data = Core.all
    end

    # @cores = @selected_data.filter(filtering_params(params)).limit(20)
    # @cores_limited = @selected_data.limit(20)
    @selected_data = @selected_data.order(updated_at: :desc)
    @cores = @selected_data.filter(filtering_params(params)).paginate(:page => params[:page], :per_page => 20)
    @cores_count = Core.count
    @selected_core_count = @selected_data.count

    cores_csv = @selected_data.order(:sfdc_id)
    respond_to do |format|
      format.html
      format.csv { render text: cores_csv.to_csv }
    end

    # Checkbox - Deprecated!
    # batch_status
  end

  # GET /cores/1
  # GET /cores/1.json
  def show
  end

  # GET /cores/new
  def new
    @core = Core.new
  end

  # Go to the CSV importing page
  def import_page
  end

  def import_core_data
    file_name = params[:file]
    Core.import_csv(file_name, Core, "bds_status")

    flash[:notice] = "CSV imported successfully."
    redirect_to cores_path
  end

  # GET /cores/1/edit
  def edit
  end

  def search
    @cores_count = Core.count
  end

  # POST /cores
  # POST /cores.json
  def create
    @core = Core.new(core_params)

    respond_to do |format|
      if @core.save
        format.html { redirect_to @core, notice: 'Core was successfully created.' }
        format.json { render :show, status: :created, location: @core }
      else
        format.html { render :new }
        format.json { render json: @core.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cores/1
  # PATCH/PUT /cores/1.json
  def update
    respond_to do |format|
      if @core.update(core_params)
        format.html { redirect_to @core, notice: 'Core was successfully updated.' }
        format.json { render :show, status: :ok, location: @core }
      else
        format.html { render :edit }
        format.json { render json: @core.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cores/1
  # DELETE /cores/1.json
  def destroy
    @core.destroy
    respond_to do |format|
      format.html { redirect_to cores_url, notice: 'Core was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def core_comp_cleaner_btn
    @service.core_comp_cleaner_btn
    flash[:notice] = "Core(Comparison) cleaned successfully."
    redirect_to cores_path
  end

  def core_power_btn

    # previously called franchiser_btn
    # !! CAUTION !!
    # @service.core_data_dumper
    # @service.delay.core_full_address_cleaner
    # @service.core_full_address_cleaner
    # @service.core_acct_name_cleaner

    # @service.phone_formatter

    # @service.geo_missing_street_num

    # @service.image_mover

    # @service.hybrid_address_matcher

    # @service.account_matcher

    # @service.core_staffer_domain_cleaner
    # @service.delay.core_staffer_domain_cleaner

    # @service.period_remover


    ### Above are Dangerous!  Use w/ Care!  ###
    #############################

    # @service.core_root_formatter

    # @service.delay.franchise_resetter
    # @service.franchise_resetter
    # @service.delay.franchise_termer
    # @service.franchise_termer
    # @service.delay.franchise_consolidator
    # @service.franchise_consolidator

    # redirect_to root_path
    redirect_to cores_path
  end

  def col_splitter_btn
    @service.col_splitter
    redirect_to root_path
  end

  def merge_data
    @service.merge_data_starter(params[:cores])
    flash[:notice] = "Merging Data Done!"
    redirect_to cores_path
  end

  def flag_data
    @service.flag_data_starter(params[:cores])
    flash[:notice] = "Flagging Data Done!"
    redirect_to cores_path
  end

  def drop_data
    @service.drop_data_starter(params[:cores])
    flash[:notice] = "Dropping Data Done!"
    redirect_to cores_path
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_core
    @core = Core.find(params[:id])
  end

  def set_core_service
    @service = CoreService.new
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def core_params
    params.require(:core).permit(:bds_status, :sfdc_id, :sfdc_tier, :sfdc_sales_person, :sfdc_type, :sfdc_ult_grp, :sfdc_group, :sfdc_acct, :sfdc_street, :sfdc_city, :sfdc_state, :sfdc_ph, :sfdc_url, :created_at, :updated_at, :indexer_date, :staffer_date, :staff_pf_sts, :loc_pf_sts, :staff_link, :staff_text, :location_link, :location_text, :staffer_sts, :sfdc_franchise, :sfdc_franch_cat, :sfdc_franch_cons, :template, :full_address, :latitude, :longitude, :geo_date, :coordinates, :geo_sts, :cop_franch, :conf_cat, :sfdc_acct_url, :sfdc_ult_grp_id, :sfdc_group_id, :img_url, :sfdc_ult_rt, :sfdc_grp_rt, :sfdc_zip, :sfdc_clean_url, :crm_acct_pin, :crm_phones, :who_sts, :match_score, :acct_match_sts, :ph_match_sts, :pin_match_sts, :url_match_sts, :acct_merge_sts, :alt_acct_pin, :alt_acct, :alt_street, :alt_city, :alt_state, :alt_zip, :alt_ph, :alt_url, :alt_source, :alt_address, :alt_template, :redirect_sts)
  end

  def filtering_params(params)
    params.slice(:bds_status, :sfdc_id, :sfdc_tier, :sfdc_sales_person, :sfdc_type, :sfdc_ult_grp, :sfdc_group, :sfdc_acct, :sfdc_street, :sfdc_city, :sfdc_state, :sfdc_ph, :staff_pf_sts, :loc_pf_sts, :staffer_sts, :sfdc_franchise, :sfdc_franch_cat, :sfdc_franch_cons, :template, :full_address, :coordinates, :geo_sts, :cop_franch, :conf_cat, :sfdc_zip, :sfdc_clean_url, :crm_acct_pin, :crm_phones, :who_sts, :match_score, :acct_match_sts, :ph_match_sts, :pin_match_sts, :url_match_sts, :acct_merge_sts, :redirect_sts)
  end

  def batch_status
    ids = params[:status_checks]
    status = params[:selected_status]
    unless ids.nil?
      for id in ids
        data = Core.find(id)
        data.update_attribute(:bds_status, status)
      end
      # Queue
      if status == 'Queue Indexer'
        start_indexer(ids)
      elsif status == 'Queue Staffer'
        start_staffer(ids)
      elsif status == 'Queue Geo'
        geo_starter(ids)
      end
    end
  end

  def start_indexer(ids)
    # IndexerService.new.delay.start_indexer(ids)
    IndexerService.new.start_indexer(ids)
    flash[:notice] = 'Indexer started!'
    redirect_to cores_path
  end

  def start_staffer(ids)
    # StafferService.new.delay.start_staffer(ids)
    StafferService.new.start_staffer(ids)

    flash[:notice] = 'Staffer started!'
    # redirect_to staffers_path
    redirect_to cores_path
  end

  def geo_starter(ids)  ## From 'Queue Geo' Batch Select

    # LocationService.new.delay.geo_starter(ids)
    LocationService.new.geo_starter(ids)

    flash[:notice] = 'Geo started!'
    redirect_to cores_path
  end

  # Get dropdown option list from Dashboard
  def set_option_list
    @alt_source_opts = ordered_list(grap_item_list("alt_source"))
    @sfdc_type_opts = ordered_list(grap_item_list("sfdc_type"))
    @sfdc_tier_opts = ordered_list(grap_item_list("sfdc_tier"))
    @sfdc_sales_person_opts = ordered_list(grap_item_list("sfdc_sales_person"))
    # @state_opts = ordered_list(grap_item_list("sfdc_state"))
    @franch_cons_opts = ordered_list(grap_item_list("sfdc_franch_cons"))
    @franch_cat_opts = ordered_list(grap_item_list("sfdc_franch_cat"))
    @template_opts = ordered_list(grap_item_list("template"))
    @bds_status_opts = ordered_list(grap_item_list("bds_status"))
    @staffer_sts_opts = ordered_list(grap_item_list("staffer_sts"))
    @acct_merge_sts_opts = ordered_list(grap_item_list("acct_merge_sts"))
    @match_score_opts = ordered_list(grap_item_list("match_score"))
    @acct_match_sts_opts = ordered_list(grap_item_list("acct_match_sts"))
    @pin_match_sts_opts = ordered_list(grap_item_list("pin_match_sts"))
    @url_match_sts_opts = ordered_list(grap_item_list("url_match_sts"))
    @ph_match_sts_opts = ordered_list(grap_item_list("ph_match_sts"))
    # @state_opts = ordered_list(grap_item_list("state"))
    @state_opts = ordered_list(list_of_states)
  end

  def grap_item_list(col_name)
    Dashboard.find_by(db_name: "Core", col_name: col_name).item_list
  end

end

app/helpers/cores_helper.rb
module CoresHelper
  def acct_merge_sts_indicator(core)
    sts = core.acct_merge_sts
    if sts == "Merge"
      html = <<-HTML
      <td class='bg-light-green geo w-xsm'>#{fa_icon 'plus shadow', class: 'fa-gray'}</td>
      HTML
    elsif sts == "Flag"
      html = <<-HTML
      <td class='bg-light-orange geo w-xsm'>#{fa_icon 'flag shadow', class: 'fa-gray'}</td>
      HTML
    elsif sts == "Drop"
      html = <<-HTML
      <td class='bg-light-red geo w-xsm'>#{fa_icon 'minus shadow', class: 'fa-gray'}</td>
      HTML
    else
      html = <<-HTML

      HTML
    end
    html.html_safe
  end

  def indicate_match(match_sts)
    if match_sts == "Same"
      "bg-light-green"
    else
      "bg-light-red"
    end
  end
end

app/views/cores/_acct_detail_1.html.erb
<table class="table table-bordered no-wrap">

  <tr>
    <!-- Checkbox / Num -->
    <!-- Dealer Website URL -->
    <th class="geo w-sm"><%= num %></th>
    <!-- account id / sfdc acct link -->
    <th>ID</th>
    <!-- bds_status -->
    <th>Core</th>
    <!-- indexer status -->
    <th colspan="2">Page Finder</th>
    <!-- staffer status -->
    <th colspan="2">Staffer</th>
    <!-- dealer website template -->
    <th>Temp</th>
    <!-- geo location status -->
    <th>Geo</th>
    <!-- CoPilot Franchise and Type -->
    <th class="geo w-xsm">Brand</th>

  </tr>
  <tr>
    <!-- tier -->
    <td><span data-toggle="tooltip" data-placement="top" title="Sales Tier"><%= core.sfdc_tier %></span></td>

    <!-- Account Icon, SFDC Link, Merge Status -->
    <% unless core.sfdc_acct_url == nil %>
    <td class="geo w-xsm fa-blue">
      <%= link_to add_http(core.sfdc_acct_url), :target => "_blank" do %>
      <%= fa_icon "address-card lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "SFDC Account ID / Link: #{core.sfdc_id}" %>
      <% end %>
    </td>
    <% else %>
    <td class="geo w-xsm fa-red"><%= fa_icon "address-card lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "NO SFDC URL" %></td>
    <% end %>

    <!-- bds_status -->
    <% unless core.updated_at == nil %>
    <td class="geo w-xsm fa-blue">
      <%= fa_icon "diamond lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "#{core.bds_status}: #{core.updated_at.strftime("%m/%d/%Y")}" %>
    </td>
    <% else %>
    <td class="geo w-xsm fa-gray">
      <%= fa_icon "diamond lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "No Status" %>
    </td>
    <% end %>


    <% if core.staff_link %>
    <td class="geo w-xsm fa-blue">
      <%= link_to core.staff_link, :target => "_blank" do %>
      <%= fa_icon "users lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "#{core.staff_text}" %>
      <% end %>
    </td>
    <% else %>
    <td class="geo w-xsm fa-gray">
      <%= fa_icon "users lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "Staff Page Not Found. Check Scraper Module." %>
    </td>
    <% end %>


    <% if core.location_link %>
    <td class="geo w-xsm fa-blue">
      <%= link_to core.location_link, :target => "_blank" do %>
      <%= fa_icon "sitemap lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "#{core.location_text}" %>
      <% end %>
    </td>
    <% else %>
    <td class="geo w-xsm fa-gray">
      <%= fa_icon "sitemap lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "Locations Page Not Found. Check Scraper Module." %>
    </td>
    <% end %>



    <!-- Trial for CRM Contacts Link and Count -->
    <% if core.crm_staff_count > 0  %>
    <td class="geo w-xsm fa-blue">
      <%= link_to staffer_acct_contacts_path(core: core), :target => "_blank" do %>
      <%= fa_icon "user-plus lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "CRM Contacts: #{core.crm_staff_count}" %>
      <% end %> <%= core.crm_staff_count %>
    </td>
    <% else %>
    <td class="geo w-xsm fa-gray">
      <%= fa_icon "user-plus lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "No CRM Contacts Linked" %>
    </td>
    <% end %>


    <!-- Trial for Web Contacts Link and Count -->
    <% if core.web_staff_count > 0  %>
    <td class="geo w-xsm fa-blue">
      <%= link_to staffer_acct_contacts_path(core: core), :target => "_blank" do %>
      <%= fa_icon "user-plus lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "Scraped Contacts: #{core.web_staff_count}" %>
      <% end %> <%= core.web_staff_count %>
    </td>
    <% else %>
    <td class="geo w-xsm fa-gray">
      <%= fa_icon "user-plus lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "No Scraped Contacts Linked" %>
    </td>
    <% end %>


    <!-- Trial for Template  -->
    <% if core.alt_template %>
    <td class="geo w-xsm fa-blue">
      <%= fa_icon "file-text lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "Dealer Template: #{core.alt_template}" %>
    </td>
    <% elsif core.template %>
    <td class="geo w-xsm fa-blue">
      <%= fa_icon "file-text lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "Dealer Template: #{core.template}" %>
    </td>
    <% else %>
    <td class="geo w-xsm fa-gray">
      <%= fa_icon "file-text lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "No Template Linked" %>
    </td>
    <% end %>


    <!-- geo location status -->
    <% if core.geo_date != nil && core.geo_sts == "Geo Result" %>
    <td class="geo w-xsm fa-blue">
      <%= fa_icon "map lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "#{core.geo_sts}:  #{core.geo_date.strftime("%m/%d/%Y")}" %>
    </td>
    <% elsif core.geo_date != nil && core.geo_sts.include?("Error") %>
    <td class="geo w-xsm fa-red">
      <%= fa_icon "map lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "#{core.geo_sts}:  #{core.geo_date.strftime("%m/%d/%Y")}" %>
    </td>
    <% else %>
    <td class="geo w-xsm fa-gray">
      <%= fa_icon "map lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "No Status" %>
    </td>
    <% end %>

    <!-- CoPilot franchise brand type & Franchise Category Icon-->
    <% if core.sfdc_franch_cons && core.sfdc_franch_cat != nil %>
    <td class="geo w-xsm fa-blue"><%= fa_icon "car lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "SDF #{core.sfdc_franch_cat}: #{core.sfdc_franch_cons}" %></td>
    <% else %>
    <td class="geo w-xsm fa-gray"><%= fa_icon "car lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "No Franchise Data" %></td>
    <% end %>

  </tr>
</table>

app/views/cores/_list_view.html.erb
<!-- <table class="list-table table table-bordered table-hover text-nowrap table-striped"> -->
<!-- <table class="table table-bordered indexer-table no-wrap"> -->
<div class="scr-prof-net scr-prof">

  <table class="table table-bordered no-wrap">

    <thead>
      <tr>
        <!-- <th><%#= check_box_tag 'check_all', 'check_all', false, onClick: 'checkAll(this);' %></th> -->
        <th>#</th>
        <!-- <th>Core</th> -->
        <!-- <th>Staff Indexer</th> -->
        <!-- <th>Location Indexer</th> -->
        <!-- <th>Staffer</th> -->
        <!-- <th>SFDC Geo</th> -->
        <!-- <th>SFDC Coord</th> -->
        <th>Staff Page</th>
        <th>Account</th>
        <th>Ult Group</th>
        <th>City</th>
        <th>State</th>
        <th>Type</th>
        <th>Salesperson</th>
        <th>SFDC ID</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% num = 0 %>
      <% @cores.each do |core| %>
      <% num +=1 %>
      <tr>
        <!-- <td><%#= check_box_tag "status_checks[]",  core.id %></td> -->
        <td><%= num %></td>
        <!-- <td><%#= core.bds_status %></td> -->
        <!-- <td><%#= core.staff_pf_sts %></td> -->
        <!-- <td><%#= core.loc_pf_sts %></td> -->
        <!-- <td><%#= core.staffer_sts %></td> -->
        <!-- <td><%#= core.geo_sts %></td> -->
        <!-- <td><%#= core.coordinates %></td> -->
        <% if core.staff_text && core.staff_text != "(none)"%>
        <td class="yes"><%= link_to core.staff_text, core.staff_link, :target => "_blank" %></td>
        <% else %>
        <td><%= core.staff_text %></td>
        <% end %>
        <td><%= core.sfdc_acct %></td>
        <td><%= core.sfdc_ult_grp %></td>
        <td><%= core.sfdc_city %></td>
        <td><%= core.sfdc_state %></td>
        <td><%= core.sfdc_type %></td>
        <td><%= core.sfdc_sales_person %></td>
        <td><%= core.sfdc_id %></td>
        <td class='details-btn' >
          <%= link_to staffer_acct_contacts_path(core: core), :target => "_blank" do %>
          <span class="glyphicon glyphicon-folder-open"></span>
          <% end %>
        </td>
        <% if advanced_and_up %>
        <td class='edit-btn' >
          <%= link_to edit_core_path(core) do %>
          <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
        </td>
        <% end %>
        <% if admin_only %>
        <td class='delete-btn' >
          <%= link_to core, method: :delete do %>
          <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/cores/edit.html.erb
<h1 class="text-center">Editing Core</h1>

<%= render 'form', core: @core %>

<%= link_to 'Show', @core, class: 'btn btn-info' %>
<%= link_to 'Back', cores_path, class: 'btn btn-primary pull-left' %>

app/views/cores/import_page.html.erb
<h1>Import a CSV File</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for CSV file</p>
    <ul>
      <li>Point 1.</li>
      <li>Point 1.</li>
      <li>Point 1.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_tag import_core_data_cores_path, multipart: true do %>
    <div class="form-group">
      <%= file_field_tag :file, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= submit_tag "Import CSV", class: 'btn btn-success' %>
    </div>
    <% end %>
  </div>
</div>

app/views/cores/new.html.erb
<h1 class="text-center">New Core</h1>

<%= render 'form', core: @core %>

<%= link_to 'Back', cores_path, class: 'btn btn-primary pull-left' %>