config/routes.rb
Rails.application.routes.draw do
  resources :whos do
    collection { post :import_csv_data }
  end
  get 'who_starter_btn' => 'whos#who_starter_btn'
  get 'who/import_page' => 'whos#import_page'
  get 'who/search' => 'whos#search'
  get 'who_power_btn' => 'whos#who_power_btn'
  
  resources :indexer_terms do
    collection { post :import_csv_data }
  end
  get 'indexer_term/import_page' => 'indexer_terms#import_page'

  resources :indexers do
    collection {post :import_csv_data}
    #   get :merge_data, on: :collection
  end
  get 'indexer/search' => 'indexers#search'
  get 'indexer/import_page' => 'indexers#import_page'
  get 'page_finder_btn' => 'indexers#page_finder_btn'
  get 'reset_errors_btn' => 'indexers#reset_errors_btn'
  get 'indexer_power_btn' => 'indexers#indexer_power_btn'
  get 'template_finder_btn' => 'indexers#template_finder_btn'
  get 'rooftop_data_getter_btn' => 'indexers#rooftop_data_getter_btn'
  get 'meta_scraper_btn' => 'indexers#meta_scraper_btn'
  get 'indexer/show_detail' => 'indexers#show_detail'
  get 'url_redirect_checker_btn' => 'indexers#url_redirect_checker_btn'
  get 'score_calculator_btn' => 'indexers#score_calculator_btn'
  get 'scraper_migrator_btn' => 'indexers#scraper_migrator_btn'

  get 'migrate_address_to_staffers_btn' => 'indexers#migrate_address_to_staffers_btn'

  get 'id_sorter_btn' => 'indexers#id_sorter_btn'
  get 'finalizer_btn' => 'indexers#finalizer_btn'
  get 'phone_formatter_finalizer_btn' => 'indexers#phone_formatter_finalizer_btn'
  get 'geo_to_indexer_btn' => 'indexers#geo_to_indexer_btn'
  get 'address_formatter_btn' => 'indexers#address_formatter_btn'
  get 'phone_migrator_btn' => 'indexers#phone_migrator_btn'


  resources :locations do
    collection {post :import_csv_data}
    get :merge_data, on: :collection
    get :flag_data, on: :collection
  end
  get 'location/import_page' => 'locations#import_page'
  get 'location/search' => 'locations#search'
  get 'geo_places_starter_btn' => 'locations#geo_places_starter_btn'
  get 'location_power_btn' => 'locations#location_power_btn'
  get 'turbo_matcher_btn' => 'locations#turbo_matcher_btn'
  get 'location_cleaner_btn' => 'locations#location_cleaner_btn'
  get 'geo_update_migrate_btn' => 'locations#geo_update_migrate_btn'
  # get 'geo_starter_btn' => 'locations#geo_starter_btn'

  resources :staffers do
    collection { post :import_csv_data }
  end
  get 'staffer/import_page' => 'staffers#import_page'
  get 'staffer/search' => 'staffers#search'
  get 'staffer/acct_contacts' => 'staffers#acct_contacts'
  get 'cs_data_getter_btn' => 'staffers#cs_data_getter_btn'
  get 'staffer_sfdc_id_cleaner_btn' => 'staffers#staffer_sfdc_id_cleaner_btn'
  get 'staffer_power_btn' => 'staffers#staffer_power_btn'
  get 'crm_staff_counter_btn' => 'staffers#crm_staff_counter_btn'

  resources :cores do
    collection { post :import_core_data }
    get :merge_data, on: :collection
    get :flag_data, on: :collection
    get :drop_data, on: :collection
  end
  get 'core/import_page' => 'cores#import_page'
  get 'core/search' => 'cores#search'
  # # Clean Data Buttons
  # get 'core_comp_cleaner_btn' => 'cores#core_comp_cleaner_btn'
  get 'core_power_btn' => 'cores#core_power_btn'
  get 'col_splitter_btn' => 'cores#col_splitter_btn'

  resources :in_host_pos do
    collection { post :import_csv_data }
  end
  get 'in_host_po/import_page' => 'in_host_pos#import_page'

  resources :dashboards do
    collection { post :import_csv_data }
  end
  get 'dashboard/import_page' => 'dashboards#import_page'
  get 'dashboard_mega_btn' => 'dashboards#dashboard_mega_btn'
  get 'cores_dash_btn' => 'dashboards#cores_dash_btn'
  get 'delayed_jobs_dash_btn' => 'dashboards#delayed_jobs_dash_btn'
  get 'franchise_dash_btn' => 'dashboards#franchise_dash_btn'
  get 'indexer_dash_btn' => 'dashboards#indexer_dash_btn'
  get 'geo_locations_dash_btn' => 'dashboards#geo_locations_dash_btn'
  get 'staffers_dash_btn' => 'dashboards#staffers_dash_btn'
  get 'users_dash_btn' => 'dashboards#users_dash_btn'
  get 'whos_dash_btn' => 'dashboards#whos_dash_btn'
  get 'summarize_data' => 'dashboards#summarize_data'
  get 'dashboard_power_btn' => 'dashboards#dashboard_power_btn'


  devise_for :users

  #==== Delayed_Jobs_Interface Starts=========
  # match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # #==== Search Pages Start=========
  post 'search_result_page_core' => 'search#search_result_core'
  post 'search_result_page_staffer' => 'search#search_result_staffer'
  post 'search_result_page_location' => 'search#search_result_location'
  post 'search_result_page_indexer' => 'search#search_result_indexer'
  post 'search_result_page_indexer' => 'search#search_result_indexer'


  get 'admin/index'
  get 'admin/starters'
  get 'admin/change_user_level' => 'admin#change_user_level'
  get 'admin/delete_user' => 'admin#delete_user'
  get 'admin/developer' => 'admin#developer'

  root 'welcome#index'


  # Hide all CRUD actions 2017.03.10 ==================================

  # # === Google API Route ===
  # get '/search' => 'search#index'

  # resources :in_text_pos do
  #     collection { post :import_csv_data }
  # end
  # get 'in_text_po/import_page' => 'in_text_pos#import_page'
end

app/views/admin/_starters_csvs.html.erb
<div id="admin-starter" class="scr-prof-net scr-prof">
  <table class="table table-bordered no-wrap">
    <thead>
      <tr>
        <th>Module</th>
        <th>Download CSV</th>
        <th>Import CSV</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Accounts</td>
        <td>
          <%= link_to cores_path(format: "csv"), class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-download" aria-hidden="true"></i> Download CSV
          <% end %>
        </td>
        <td>
          <%= link_to core_import_page_path, class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-folder-open" aria-hidden="true"></i> Import CSV
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Contacts</td>
        <td>
          <%= link_to staffers_path(format: "csv"), class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-download" aria-hidden="true"></i> Download CSV
          <% end %>
        </td>
        <td>
          <%= link_to staffer_import_page_path, class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-folder-open" aria-hidden="true"></i> Import CSV
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Scraper</td>
        <td>
          <%= link_to indexers_path(format: "csv"), class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-download" aria-hidden="true"></i> Download CSV
          <% end %>
        </td>
        <td>
          <%= link_to indexer_import_page_path, class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-folder-open" aria-hidden="true"></i> Import CSV
          <% end %>
        </td>
      </tr>
      <tr>
        <td>WhoIs</td>
        <td>
          <%= link_to whos_path(format: "csv"), class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-download" aria-hidden="true"></i> Download CSV
          <% end %>
        </td>
        <td>
          <%= link_to who_import_page_path, class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-folder-open" aria-hidden="true"></i> Import CSV
          <% end %>
        </td>
      </tr>
      <tr>
        <td>GeoLocations</td>
        <td>
          <%= link_to locations_path(format: "csv"), class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-download" aria-hidden="true"></i> Download CSV
          <% end %>
        </td>
        <td>
          <%= link_to location_import_page_path, class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-folder-open" aria-hidden="true"></i> Import CSV
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Dashboards</td>
        <td>
          <%= link_to dashboards_path(format: "csv"), class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-download" aria-hidden="true"></i> Download CSV
          <% end %>
        </td>
        <td>
          <%= link_to dashboard_import_page_path, class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-folder-open" aria-hidden="true"></i> Import CSV
          <% end %>
        </td>
      </tr>
      <tr><th>Admin</th><th></th><th></th></tr>
      <tr>
        <td>Franchises List</td>
        <td>
          <%= link_to in_host_pos_path(format: "csv"), class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-download" aria-hidden="true"></i> Download CSV
          <% end %>
        </td>
        <td>
          <%= link_to in_host_po_import_page_path, class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-folder-open" aria-hidden="true"></i> Import CSV
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Scraper Criteria</td>
        <td>
          <%= link_to indexer_terms_path(format: "csv"), class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-download" aria-hidden="true"></i> Download CSV
          <% end %>
        </td>
        <td>
          <%= link_to indexer_term_import_page_path, class: 'btn btn-primary btn-xs' do %>
          <i class="fa fa-folder-open" aria-hidden="true"></i> Import CSV
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div><br>

app/views/admin/_starters_dashboard.html.erb
<div id="admin-starter" class="scr-prof-net scr-prof">
  <table class="table table-bordered no-wrap">
    <tr><th colspan="2">Dashboard Calculators</th></tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to dashboard_mega_btn_path, class: 'btn btn-green btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> MEGA Stats
        <% end %>
      </td>
    </tr>
  </table><br>

  <table class="table table-bordered no-wrap">
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to cores_dash_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Account Stats
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to staffers_dash_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Contact Stats
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to franchise_dash_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Franchise Stats
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to geo_locations_dash_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> GeoLocation Stats
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to indexer_dash_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Indexer Stats
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to whos_dash_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> WhoIs Stats
        <% end %>
      </td>
    </tr>
  </table>
</div><br>

app/views/admin/_starters_finalizer.html.erb
<div id="admin-starter" class="scr-prof-net scr-prof">
  <table class="table table-bordered no-wrap">
    <tr><th colspan="2">Finalizers</th></tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to finalizer_btn_path, class: 'btn btn-xs btn-width btn-green' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Finalizer
        <% end %>
      </td>
    </tr>
  </table><br>

  <table class="table table-bordered no-wrap">
    <tr>
      <td>1. Description...</td>
      <td>
        <%= link_to id_sorter_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Id Sorter
        <% end %>
      </td>

    </tr>
    <tr>
      <td>2. Description...</td>
      <td>
        <%= link_to score_calculator_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Score Calculator
        <% end %>
      </td>
    </tr>
    <tr>
      <td>3. Description...</td>
      <td>
        <%= link_to scraper_migrator_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Scraper Migrator
        <% end %>
      </td>
    </tr>
    <tr>
      <td>4. Migrates Account Addresses to Contacts Table</td>
      <td>
        <%= link_to migrate_address_to_staffers_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Cont. Addr. Migrator
        <% end %>
      </td>
    </tr>
  </table>
</div><br>

app/views/admin/_starters_formatter.html.erb
<div id="admin-starter" class="scr-prof-net scr-prof">
  <table class="table table-bordered no-wrap">
    <tr><th colspan="2">Formatter</th></tr>
    <tr>
      <td>Description</td>
      <td>
        <%= link_to crm_staff_counter_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> CRM Staff Counter
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to phone_formatter_finalizer_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Phone Formatter
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Migrates account url, acct, phone, pin, addr, street, city, state, zip from geo to indexer IF indexer rts results are Meta or if account name is nil, based on same clean_url.</td>
      <td>
        <%= link_to geo_to_indexer_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Geo Migrator
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Migrates full_addr, street, city, state, zip from geo to indexer IF clean_url and acct pin same.</td>
      <td>
        <%= link_to address_formatter_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Address Formatter
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Migrates geo phone to Indexer if indexer phone is nil, and indexer and geo share same clean_url.</td>
      <td>
        <%= link_to phone_migrator_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Phone Migrator
        <% end %>
      </td>
    </tr>


  </table>
</div><br>

app/views/admin/_starters_location.html.erb
<div id="admin-starter" class="scr-prof-net scr-prof">
  <table class="table table-bordered no-wrap">
    <tr><th colspan="2">Location Buttons</th></tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to geo_places_starter_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Places Starter
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to turbo_matcher_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i> Auto-Matcher
        <% end %>
      </td>
    </tr>
  </table>
</div><br>

app/views/admin/_starters_power.html.erb
<!-- BY DEFAULT THESE BUTTONS SHOULD BE DISABLED.  ONLY ENABLE ON CASE-BY-CASE TEMPORARILY -->

<div id="admin-starter" class="scr-prof-net scr-prof">
  <table class="table table-bordered no-wrap">
    <tr><th colspan="3">Power Buttons</th></tr>
    <tr>
      <td>
        <%= link_to core_power_btn_path, class: 'btn btn-orange btn-xs btn-width' do %>
        <i class="fa fa-magic" aria-hidden="true"></i> Core Power
        <% end %>
      </td>
      <td>
        <%= link_to staffer_power_btn_path, class: 'btn btn-orange btn-xs btn-width' do %>
        <i class="fa fa-magic" aria-hidden="true"></i> Staffer Power
        <% end %>
      </td>
      <td>
        <%= link_to indexer_power_btn_path, class: 'btn btn-orange btn-xs btn-width' do %>
        <i class="fa fa-magic" aria-hidden="true"></i> Indexer Power
        <% end %>
      </td>
    </tr>

    <tr>
      <td>
        <%= link_to who_power_btn_path, class: 'btn btn-orange btn-xs btn-width' do %>
        <i class="fa fa-magic" aria-hidden="true"></i> Who Power
        <% end %>
      </td>
      <td>
        <%= link_to location_power_btn_path, class: 'btn btn-orange btn-xs btn-width' do %>
        <i class="fa fa-magic" aria-hidden="true"></i> Location Power
        <% end %>
      </td>
      <td>
        <%= link_to dashboard_power_btn_path, class: 'btn btn-orange btn-xs btn-width' do %>
        <i class="fa fa-magic" aria-hidden="true"></i> Dashboard Power
        <% end %>
      </td>
    </tr>

  </table>
</div><br>

<!-- BY DEFAULT THESE BUTTONS SHOULD BE DISABLED.  ONLY ENABLE ON CASE-BY-CASE TEMPORARILY -->

app/views/admin/_starters_scraper.html.erb
<div id="admin-starter" class="scr-prof-net scr-prof">
  <table class="table table-bordered no-wrap">
    <tr><th colspan="2">Scraper Starters</th></tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to url_redirect_checker_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i>  URL Redirector
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to who_starter_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i>  WhoIs Search
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to template_finder_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i>  Template Finder
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to page_finder_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i>  Page Finder
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to rooftop_data_getter_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i>  Rooftop Scraper
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to meta_scraper_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i>  Meta Scraper
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Description...</td>
      <td>
        <%= link_to cs_data_getter_btn_path, class: 'btn btn-primary btn-xs btn-width' do %>
        <i class="fa fa-circle-o-notch" aria-hidden="true"></i>  Staff Scraper
        <% end %>
      </td>
    </tr>
  </table>
</div><br>

app/views/admin/_table.html.erb
<div class="scr-prof-net scr-prof">
  <table class="table table-bordered no-wrap">
    <thead>
      <tr>
        <th class="level-heading"><%= header %></th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Work Phone</th>
        <th>Mobile Phone</th>
        <th>Department</th>
        <th class="manage-btn">Manage</th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
      <tr>
        <td data-id="<%= user.id %>" onClick="selectUsers(this);">
          <%= fa_icon "check lg", class: "stat-btn fa-clear" %>
        </td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.work_phone %></td>
        <td><%= user.mobile_phone %></td>
        <td><%= user.department %></td>
        <td class='bg-light-red' >
          <%= link_to admin_delete_user_path(user: user), data: { confirm: 'Are you sure to delete this user?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div><br>

app/views/admin/developer.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Developer Only</h1>

    <!-- Scraper buttons -->
    <%= render partial: 'starters_scraper' %>

    <!-- Formatter buttons -->
    <%= render partial: 'starters_formatter' %>

    <!-- Finalizer buttons -->
    <%= render partial: 'starters_finalizer' %>

    <!-- Dashboard buttons -->
    <%= render partial: 'starters_dashboard' %>

    <!-- Location buttons -->
    <%#= render partial: 'starters_location' %>

    <!-- Power buttons for development -->
    <%= render partial: 'starters_power' %>

  </div>
</div>

app/views/admin/index.html.erb
<div class="row text-center pageHeading">
  <div class="col-md-3">
    <h1>Admin</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render partial: 'table', locals: { users: @pending_users, header: "Pending" } %>
    <%= render partial: 'table', locals: { users: @basic_users, header: "Basic" } %>
    <%= render partial: 'table', locals: { users: @intermediate_users, header: "Intermediate" } %>
    <%= render partial: 'table', locals: { users: @advanced_users, header: "Advanced" } %>
    <%= render partial: 'table', locals: { users: @admin_users, header: "Admin" } %>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-12">
    <div class="pull-left scr-prof level-change-btns">
      <h4 class="inlined">Update </h4>
      <span class="btn btn-primary btn-xs" data-level="pending" onClick="changeUserLevel(this);">Pending</span>
      <span class="btn btn-primary btn-xs" data-level="basic" onClick="changeUserLevel(this);">Basic</span>
      <span class="btn btn-primary btn-xs" data-level="intermediate" onClick="changeUserLevel(this);">Intermediate</span>
      <span class="btn btn-primary btn-xs" data-level="advanced" onClick="changeUserLevel(this);">Advanced</span>
      <span class="btn btn-primary btn-xs" data-level="admin" onClick="changeUserLevel(this);">Admin</span>
    </div>
  </div>
</div>

app/views/admin/starters.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>System Starters -  Admin Only</h1>
    <!-- Import/Export CSV buttons for modules -->
    <%= render partial: 'starters_csvs' %>
  </div>
</div>