config/routes.rb
Rails.application.routes.draw do
  resources :whos do
    collection { post :import_csv_data }
  end
  get 'who_starter_btn' => 'whos#who_starter_btn'
  get 'who/import_page' => 'whos#import_page'
  get 'who/search' => 'whos#search'
  get 'who_power_btn' => 'whos#who_power_btn'
  
  resources :indexer_terms do
    collection { post :import_csv_data }
  end
  get 'indexer_term/import_page' => 'indexer_terms#import_page'

  resources :indexers do
    collection {post :import_csv_data}
    #   get :merge_data, on: :collection
  end
  get 'indexer/search' => 'indexers#search'
  get 'indexer/import_page' => 'indexers#import_page'
  get 'page_finder_btn' => 'indexers#page_finder_btn'
  get 'reset_errors_btn' => 'indexers#reset_errors_btn'
  get 'indexer_power_btn' => 'indexers#indexer_power_btn'
  get 'template_finder_btn' => 'indexers#template_finder_btn'
  get 'rooftop_data_getter_btn' => 'indexers#rooftop_data_getter_btn'
  get 'meta_scraper_btn' => 'indexers#meta_scraper_btn'
  get 'indexer/show_detail' => 'indexers#show_detail'
  get 'url_redirect_checker_btn' => 'indexers#url_redirect_checker_btn'
  get 'score_calculator_btn' => 'indexers#score_calculator_btn'
  get 'scraper_migrator_btn' => 'indexers#scraper_migrator_btn'

  get 'migrate_address_to_staffers_btn' => 'indexers#migrate_address_to_staffers_btn'

  get 'id_sorter_btn' => 'indexers#id_sorter_btn'
  get 'finalizer_btn' => 'indexers#finalizer_btn'
  get 'phone_formatter_finalizer_btn' => 'indexers#phone_formatter_finalizer_btn'
  get 'geo_to_indexer_btn' => 'indexers#geo_to_indexer_btn'
  get 'address_formatter_btn' => 'indexers#address_formatter_btn'
  get 'phone_migrator_btn' => 'indexers#phone_migrator_btn'


  resources :locations do
    collection {post :import_csv_data}
    get :merge_data, on: :collection
    get :flag_data, on: :collection
  end
  get 'location/import_page' => 'locations#import_page'
  get 'location/search' => 'locations#search'
  get 'geo_places_starter_btn' => 'locations#geo_places_starter_btn'
  get 'location_power_btn' => 'locations#location_power_btn'
  get 'turbo_matcher_btn' => 'locations#turbo_matcher_btn'
  get 'location_cleaner_btn' => 'locations#location_cleaner_btn'
  get 'geo_update_migrate_btn' => 'locations#geo_update_migrate_btn'
  # get 'geo_starter_btn' => 'locations#geo_starter_btn'

  resources :staffers do
    collection { post :import_csv_data }
  end
  get 'staffer/import_page' => 'staffers#import_page'
  get 'staffer/search' => 'staffers#search'
  get 'staffer/acct_contacts' => 'staffers#acct_contacts'
  get 'cs_data_getter_btn' => 'staffers#cs_data_getter_btn'
  get 'staffer_sfdc_id_cleaner_btn' => 'staffers#staffer_sfdc_id_cleaner_btn'
  get 'staffer_power_btn' => 'staffers#staffer_power_btn'
  get 'crm_staff_counter_btn' => 'staffers#crm_staff_counter_btn'

  resources :cores do
    collection { post :import_core_data }
    get :merge_data, on: :collection
    get :flag_data, on: :collection
    get :drop_data, on: :collection
  end
  get 'core/import_page' => 'cores#import_page'
  get 'core/search' => 'cores#search'
  # # Clean Data Buttons
  # get 'core_comp_cleaner_btn' => 'cores#core_comp_cleaner_btn'
  get 'core_power_btn' => 'cores#core_power_btn'
  get 'col_splitter_btn' => 'cores#col_splitter_btn'

  resources :in_host_pos do
    collection { post :import_csv_data }
  end
  get 'in_host_po/import_page' => 'in_host_pos#import_page'

  resources :dashboards do
    collection { post :import_csv_data }
  end
  get 'dashboard/import_page' => 'dashboards#import_page'
  get 'dashboard_mega_btn' => 'dashboards#dashboard_mega_btn'
  get 'cores_dash_btn' => 'dashboards#cores_dash_btn'
  get 'delayed_jobs_dash_btn' => 'dashboards#delayed_jobs_dash_btn'
  get 'franchise_dash_btn' => 'dashboards#franchise_dash_btn'
  get 'indexer_dash_btn' => 'dashboards#indexer_dash_btn'
  get 'geo_locations_dash_btn' => 'dashboards#geo_locations_dash_btn'
  get 'staffers_dash_btn' => 'dashboards#staffers_dash_btn'
  get 'users_dash_btn' => 'dashboards#users_dash_btn'
  get 'whos_dash_btn' => 'dashboards#whos_dash_btn'
  get 'summarize_data' => 'dashboards#summarize_data'
  get 'dashboard_power_btn' => 'dashboards#dashboard_power_btn'


  devise_for :users

  #==== Delayed_Jobs_Interface Starts=========
  # match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # #==== Search Pages Start=========
  post 'search_result_page_core' => 'search#search_result_core'
  post 'search_result_page_staffer' => 'search#search_result_staffer'
  post 'search_result_page_location' => 'search#search_result_location'
  post 'search_result_page_indexer' => 'search#search_result_indexer'
  post 'search_result_page_indexer' => 'search#search_result_indexer'


  get 'admin/index'
  get 'admin/starters'
  get 'admin/change_user_level' => 'admin#change_user_level'
  get 'admin/delete_user' => 'admin#delete_user'
  get 'admin/developer' => 'admin#developer'

  root 'welcome#index'


  # Hide all CRUD actions 2017.03.10 ==================================

  # # === Google API Route ===
  # get '/search' => 'search#index'

  # resources :in_text_pos do
  #     collection { post :import_csv_data }
  # end
  # get 'in_text_po/import_page' => 'in_text_pos#import_page'
end

app/models/staffer.rb
class Staffer < ApplicationRecord
  include Filterable
  include CSVTool

  # == Multi-Select Search ==
  scope :staffer_status, -> (staffer_status) { where staffer_status: staffer_status }
  scope :sfdc_sales_person, -> (sfdc_sales_person) { where sfdc_sales_person: sfdc_sales_person }
  scope :sfdc_type, -> (sfdc_type) { where sfdc_type: sfdc_type }
  scope :sfdc_tier, -> (sfdc_tier) { where sfdc_tier: sfdc_tier }
  scope :cont_status, -> (cont_status) { where cont_status: cont_status }
  scope :cont_source, -> (cont_source) { where cont_source: cont_source }
  scope :job, -> (job) { where job: job }
  scope :state, -> (state) { where state: state }

  # == Key Word Search ==
  scope :sfdc_id, -> (sfdc_id) { where("sfdc_id like ?", "%#{sfdc_id}%") }
  scope :acct_name, -> (acct_name) { where("acct_name like ?", "%#{acct_name}%") }
  scope :street, -> (street) { where("street like ?", "%#{street}%") }
  scope :city, -> (city) { where("city like ?", "%#{city}%") }
  scope :zip, -> (zip) { where("zip like ?", "%#{zip}%") }
  scope :sfdc_cont_id, -> (sfdc_cont_id) { where("sfdc_cont_id like ?", "%#{sfdc_cont_id}%") }
  scope :fname, -> (fname) { where("fname like ?", "%#{fname}%") }
  scope :lname, -> (lname) { where("lname like ?", "%#{lname}%") }
  scope :fullname, -> (fullname) { where("fullname like ?", "%#{fullname}%") }
  scope :job_raw, -> (job_raw) { where("job_raw like ?", "%#{job_raw}%") }
  scope :phone, -> (phone) { where("phone like ?", "%#{phone}%") }
  scope :email, -> (email) { where("email like ?", "%#{email}%") }
  scope :staffer_date, -> (staffer_date) { where("staffer_date like ?", "%#{staffer_date}%") }
  scope :staff_link, -> (staff_link) { where("staff_link like ?", "%#{staff_link}%") }
  scope :domain, -> (domain) { where("domain like ?", "%#{domain}%") }
  scope :acct_pin, -> (acct_pin) { where("acct_pin like ?", "%#{acct_pin}%") }
  scope :cont_pin, -> (cont_pin) { where("cont_pin like ?", "%#{cont_pin}%") }

end

app/controllers/staffers_controller.rb
class StaffersController < ApplicationController
  before_action :intermediate_and_up, only: [:index, :show, :search, :acct_contacts]
  before_action :advanced_and_up, only: [:edit, :update]
  before_action :admin_only, only: [:new, :create, :destroy, :import_page, :import_csv_data, :staffer_sfdc_id_cleaner_btn, :cs_data_getter_btn, :staffer_power_btn, :crm_staff_counter_btn]
  before_action :set_staffer, only: [:show, :edit, :update, :destroy]
  before_action :set_staffer_service, only: [:staffer_sfdc_id_cleaner_btn, :cs_data_getter_btn, :staffer_power_btn, :crm_staff_counter_btn]
  before_action :set_option_list, only: [:index, :search]

  # GET /staffers
  # GET /staffers.json

  def index
    if choice_hash = get_selected_status_staffer
      clean_choice_hash = {}
      @view_mode = choice_hash[:view_mode]

      choice_hash.each do |key, value|
        clean_choice_hash[key] = value if !value.nil? && value != "" && key != :view_mode
      end
      @selected_data = Staffer.where(clean_choice_hash)
    else # choice_hash is nil
      @selected_data = Staffer.all.order(updated_at: :desc)
    end

    if url = params[:url]
      @selected_data = @selected_data.where(domain: url).order(updated_at: :desc)
    else
      @selected_data = @selected_data.order(updated_at: :desc)
    end
    @staffer_count = Staffer.count
    @selected_staffer_count = @selected_data.count

    # CSV #
    respond_to do |format|
      format.html
      format.csv { render text: @selected_data.to_csv }
    end

    @staffers = @selected_data.filter(filtering_params(params)).paginate(:page => params[:page], :per_page => 40)

    batch_status
  end

  # GET /staffers/1
  # GET /staffers/1.json
  def show
  end

  # GET /staffers/new
  def new
    @staffer = Staffer.new
  end

  # Go to the CSV importing page
  def import_page
  end

  def import_csv_data
    file_name = params[:file]
    Staffer.import_csv(file_name, Staffer, "staffer_status")

    flash[:notice] = "CSV imported successfully."
    redirect_to staffers_path
  end


  # GET /staffers/1/edit
  def edit
  end

  def search
    @staffer_count = Staffer.count
  end


  # POST /staffers
  # POST /staffers.json
  def create
    @staffer = Staffer.new(staffer_params)

    respond_to do |format|
      if @staffer.save
        format.html { redirect_to @staffer, notice: 'Staffer was successfully created.' }
        format.json { render :show, status: :created, location: @staffer }
      else
        format.html { render :new }
        format.json { render json: @staffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffers/1
  # PATCH/PUT /staffers/1.json
  def update
    respond_to do |format|
      if @staffer.update(staffer_params)
        format.html { redirect_to @staffer, notice: 'Staffer was successfully updated.' }
        format.json { render :show, status: :ok, location: @staffer }
      else
        format.html { render :edit }
        format.json { render json: @staffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffers/1
  # DELETE /staffers/1.json
  def destroy
    @staffer.destroy
    respond_to do |format|
      format.html { redirect_to staffers_url, notice: 'Staffer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def acct_contacts
    if core_id = params[:core]
      @core = Core.find(core_id)
      @staffers = Staffer.where(sfdc_id: @core.sfdc_id)
    else
      indexer = Indexer.find(params[:indexer])
      @staffers = Staffer.where(domain: indexer.clean_url)
    end
  end

  def crm_staff_counter_btn
    @staffer_service.crm_staff_counter
    # @staffer_service.delay.crm_staff_counter
    redirect_to cores_path
  end


  def staffer_sfdc_id_cleaner_btn
    # @staffer_service.staffer_sfdc_id_cleaner

    # @staffer_service.staffer_core_updater
    # @staffer_service.delay.staffer_core_updater


    redirect_to root_path
  end


  ############## ATTENTION!!! ###############
  ### NEED TO REFACTOR THIS AFTER TESTING ###

  ### Step 1 of Staffer Scraper - Starts Here
  def cs_data_getter_btn
    ## Need to change name of this method and btn to starter, which calls the starter method which calls the cs_data_getter method in batches, based on template, then cuts into smaller jobs of 25 indexers each (25 urls.)

    # @staffer_service.cs_data_getter
    # @staffer_service.delay.cs_data_getter

    @staffer_service.cs_starter

    redirect_to indexers_path
    # redirect_to admin_path
  end

  ##########################################


  # ========== Temporary/Power Button ==========

  def staffer_power_btn
    # @staffer_service.fname_cleaner
    # @staffer_service.delay.fname_cleaner

    redirect_to indexers_path
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_staffer
    @staffer = Staffer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def staffer_params
    params.require(:staffer).permit(:staffer_status, :cont_status, :cont_source, :sfdc_id, :sfdc_sales_person, :sfdc_type, :sfdc_cont_id, :staffer_date, :created_at, :updated_at, :sfdc_tier, :domain, :acct_name, :street, :city, :state, :zip, :fname, :lname, :fullname, :job, :job_raw, :phone, :email, :full_address, :acct_pin, :cont_pin)
  end

  def filtering_params(params)
    params.slice(:staffer_status, :cont_status, :cont_source, :sfdc_id, :sfdc_sales_person, :sfdc_type, :sfdc_cont_id, :staffer_date, :created_at, :updated_at, :sfdc_tier, :domain, :acct_name, :street, :city, :state, :zip, :fname, :lname, :fullname, :job, :job_raw, :phone, :email, :full_address, :acct_pin, :cont_pin)
  end

  def batch_status
    ids = params[:multi_checks]
    return if ids.nil?
    status = params[:selected_status]
    for id in ids
      staff = Staffer.find(id)
      staff.update_attribute(:staffer_status, status)
      flash[:notice] = "Successfully updated"

      # *** Uncomment after Core Migration new staffer columns
      # core = Core.find_by(sfdc_id: staffer.sfdc_id)
      # core.update_attribute(:staffer_status, status)
    end

    destroy_rows(ids) if status == "Destroy"
  end

  def destroy_rows(ids)
    rows = Staffer.where(id: ids)
    rows.destroy_all
  end

  def set_staffer_service
    @staffer_service = StafferService.new
  end

  # Get dropdown option list from Dashboard
  def set_option_list
    @staffer_status_opts = ordered_list(grap_item_list("staffer_status"))
    @cont_source_opts = ordered_list(grap_item_list("cont_source"))
    @sfdc_type_opts = ordered_list(grap_item_list("sfdc_type"))
    @sfdc_tier_opts = ordered_list(grap_item_list("sfdc_tier"))
    @sfdc_sales_person_opts = ordered_list(grap_item_list("sfdc_sales_person"))
    @cont_status_opts = ordered_list(grap_item_list("cont_status"))
    @job_opts = ordered_list(grap_item_list("job"))
    # @state_opts = ordered_list(grap_item_list("state"))
    @state_opts = ordered_list(list_of_states)
    @email_status = ordered_list(email_status_list)
  end

  def grap_item_list(col_name)
    Dashboard.find_by(db_name: "Staffer", col_name: col_name).item_list
  end


end

app/helpers/staffers_helper.rb
module StaffersHelper
  def grap_right_core(staffer)
    src = staffer.cont_source
    if src == "CRM"
      Core.find_by(sfdc_id: staffer.sfdc_id)
    elsif src == "Web"
      Core.find_by(sfdc_clean_url: staffer.domain)
    end
  end

  def grap_right_staffers(staffer)
    src = staffer.cont_source
    if src == "CRM"
      Staffer.where(sfdc_id: staffer.sfdc_id)
    elsif src == "Web"
      Staffer.where(domain: staffer.domain)
    end
  end

end

app/views/staffers/_buttons.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="pull-right">
      <% if advanced_and_up %>
      <%= link_to 'Download CSV', staffers_path(format: "csv"), class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div><br>

app/views/staffers/_core_staffs.html.erb
<div class="scr-prof">
  <table class="table table-bordered no-wrap">

    <thead>
      <tr>
        <th>#</th>
        <!-- <th>Stage</th> -->
        <!-- <th>Status</th> -->
        <th>Source</th>
        <th>ID</th>
        <th>ID</th>
        <th>URL</th>
        <th>URL</th>
        <!-- <th>Account Name</th> -->
        <th>First Name</th>
        <th>Last Name</th>
        <th>Full Name</th>
        <th>Title</th>
        <th>Description</th>
        <th>Email</th>
        <th>Phone</th>
        <!-- <th colspan="2"></th> -->
      </tr>
    </thead>

    <tbody>
      <% num = 0 %>
      <% staffers.each do |staffer| %>
      <% num +=1 %>
      <tr>
        <td class="staffer-w-xsm"><%= num %></td>
        <!-- <td><%#= staffer.staffer_status %></td> -->
        <!-- <td><%#= staffer.cont_status %></td> -->
        <td class="staffer-w-sm"><%= staffer.cont_source %></td>

        <!-- Account ID -->
        <% unless staffer.sfdc_id == nil %>
        <td class="staffer-w-xsm fa-blue">
          <%= fa_icon "address-card lg", "data-toggle": "tooltip", "data-placement": "top", title: "#{staffer.sfdc_id}" %>
        </td>
        <% else %>
        <td class="staffer-w-xsm fa-gray"><%= fa_icon "address-card lg", "data-toggle": "tooltip", "data-placement": "top", title: "No Account ID" %></td>
        <% end %>


        <!-- Contact ID -->
        <% unless staffer.sfdc_cont_id == nil %>
        <td class="staffer-w-xsm fa-blue">
          <%= fa_icon "user lg", "data-toggle": "tooltip", "data-placement": "top", title: "#{staffer.sfdc_cont_id}" %>
        </td>
        <% else %>
        <td class="staffer-w-xsm fa-gray"><%= fa_icon "user lg", "data-toggle": "tooltip", "data-placement": "top", title: "No Contact ID" %></td>
        <% end %>


        <!-- Dealer Website Module -->
        <% if staffer.domain != nil %>
        <td class="staffer-w-xsm fa-blue">
          <span class="modalButton" data-toggle="modal" data-target="#myModal" data-src="<%= add_http(staffer.domain) %>">
            <%= fa_icon "clone lg", "data-toggle": "tooltip", "data-placement": "top", title: "LightBox: Dealer Site" %></span></span>
          </td>
          <% else %>
          <td class="staffer-w-xsm fa-red"><%= fa_icon "clone lg", "data-toggle": "tooltip", "data-placement": "top", title: "No URL" %></td>
          <% end %>


          <!-- Dealer Website External Link -->
          <% unless staffer.domain == nil %>
          <td class="staffer-w-xsm fa-blue">
            <%= link_to add_http(staffer.domain), :target => "_blank" do %>
            <%= fa_icon "external-link lg", "data-toggle": "tooltip", "data-placement": "top", title: "#{staffer.domain}" %>
            <% end %>
          </td>
          <% else %>
          <td class="staffer-w-xsm fa-red"><%= fa_icon "external-link lg", "data-toggle": "tooltip", "data-placement": "top", title: "No URL" %></td>
          <% end %>

          <!-- <td><%#= staffer.acct_name %></td> -->

          <td><%= staffer.fname %></td>
          <td><%= staffer.lname %></td>
          <td><%= staffer.fullname %></td>
          <td><%= staffer.job %></td>
          <td><%= staffer.job_raw %></td>

          <td class="staffer-w-md"><%= staffer.email %></td>

          <!-- phone -->
          <% unless staffer.phone == nil %>
          <td class="staffer-w-xsm fa-blue">
            <%= fa_icon "phone lg", "data-toggle": "tooltip", "data-placement": "top", title: "#{staffer.phone}" %>
          </td>
          <% else %>
          <td class="staffer-w-xsm fa-gray">
            <%= fa_icon "phone lg", "data-toggle": "tooltip", "data-placement": "top", title: "No Phone" %>
          </td>
          <% end %>

          <!-- <% if advanced_and_up %>
          <td><%#= link_to 'Edit', edit_staffer_path(staffer) %></td>
          <% end %>
          <% if admin_only %>
          <td><%#= link_to 'Destroy', staffer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %> -->
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="modal fade" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <div class="close-button">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" frameborder="0"></iframe>
          </div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

app/views/staffers/_detailed_view.html.erb
<% urls = [] %>
<% @staffers.each do |staffer| %>
<% domain = staffer.domain %>
<% if !urls.include?(domain) %>
<% urls << domain %>
<% if core = grap_right_core(staffer) %>
<%= render partial: 'cores/acct_profile', locals: { core: core, num: "" } %>
<% else %>
<div id="core-detail" class="text-nowrap geo-result-table bg-blue">
  <p class="lead auto-margin">Account Not Merged Yet</p>
</div><br>
<% end %>
<%= render partial: 'core_staffs', locals: { staffers: grap_right_staffers(staffer) } %>
<% end %>
<% end %>

app/views/staffers/_list_view.html.erb
<div class="scr-prof">
  <table class="table table-bordered no-wrap">

    <thead>
      <tr>
        <th>#</th>
        <!-- <th>Stage</th> -->
        <!-- <th>Status</th> -->
        <th>Source</th>
        <th>ID</th>
        <th>ID</th>
        <th>URL</th>
        <th>URL</th>
        <th>State</th>
        <th>Account Name</th>
        <th>Title</th>
        <th>Description</th>
        <th>First Name</th>
        <th>Last Name</th>
        <!-- <th>Full Name</th> -->
        <th>Email</th>
        <th>Phone</th>
        <th>Scraped</th>
        <!-- <th colspan="2"></th> -->
      </tr>
    </thead>

    <tbody>
      <% num = 0 %>
      <% staffers.each do |staffer| %>
      <% num +=1 %>
      <tr>
        <td class="staffer-w-xsm"><%= num %></td>
        <!-- <td><%#= staffer.staffer_status %></td> -->
        <!-- <td><%#= staffer.cont_status %></td> -->
        <td class="staffer-w-sm"><%= staffer.cont_source %></td>

        <!-- Account ID -->
        <% unless staffer.sfdc_id == nil %>
        <td class="staffer-w-xsm fa-blue">
          <%= fa_icon "address-card lg", "data-toggle": "tooltip", "data-placement": "top", title: "#{staffer.sfdc_id}" %>
        </td>
        <% else %>
        <td class="staffer-w-xsm fa-gray"><%= fa_icon "address-card lg", "data-toggle": "tooltip", "data-placement": "top", title: "No Account ID" %></td>
        <% end %>


        <!-- Contact ID -->
        <% unless staffer.sfdc_cont_id == nil %>
        <td class="staffer-w-xsm fa-blue">
          <%= fa_icon "user lg", "data-toggle": "tooltip", "data-placement": "top", title: "#{staffer.sfdc_cont_id}" %>
        </td>
        <% else %>
        <td class="staffer-w-xsm fa-gray"><%= fa_icon "user lg", "data-toggle": "tooltip", "data-placement": "top", title: "No Contact ID" %></td>
        <% end %>


        <!-- Dealer Website Module -->
        <% if staffer.domain != nil %>
        <td class="staffer-w-xsm fa-blue">
          <span class="modalButton" data-toggle="modal" data-target="#myModal" data-src="<%= add_http(staffer.domain) %>">
            <%= fa_icon "clone lg", "data-toggle": "tooltip", "data-placement": "top", title: "LightBox: Dealer Site" %></span></span>
          </td>
          <% else %>
          <td class="staffer-w-xsm fa-red"><%= fa_icon "clone lg", "data-toggle": "tooltip", "data-placement": "top", title: "No URL" %></td>
          <% end %>


          <!-- Dealer Website External Link -->
          <% unless staffer.domain == nil %>
          <td class="staffer-w-xsm fa-blue">
            <%= link_to add_http(staffer.domain), :target => "_blank" do %>
            <%= fa_icon "external-link lg", "data-toggle": "tooltip", "data-placement": "top", title: "#{staffer.domain}" %>
            <% end %>
          </td>
          <% else %>
          <td class="staffer-w-xsm fa-red"><%= fa_icon "external-link lg", "data-toggle": "tooltip", "data-placement": "top", title: "No URL" %></td>
          <% end %>

          <td><%= staffer.state %></td>


          <td><%= staffer.acct_name %></td>
          <td><%= staffer.job %></td>
          <td><%= staffer.job_raw %></td>

          <td><%= staffer.fname %></td>
          <td><%= staffer.lname %></td>
          <!-- <td><%#= staffer.fullname %></td> -->

          <td class="staffer-w-md"><%= staffer.email %></td>
          <td class="staffer-w-md"><%= staffer.phone %></td>

          <td class="staffer-w-md">
            <% if staffer.scrape_date %>
              <%= staffer.scrape_date.strftime("%m/%d/%y") %>
            <% end %>
          </td>

          <!-- <% if advanced_and_up %>
          <td><%#= link_to 'Edit', edit_staffer_path(staffer) %></td>
          <% end %>
          <% if admin_only %>
          <td><%#= link_to 'Destroy', staffer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %> -->
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="modal fade" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <div class="close-button">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" frameborder="0"></iframe>
          </div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->