config/routes.rb
Rails.application.routes.draw do
  resources :whos do
    collection { post :import_csv_data }
  end
  get 'who_starter_btn' => 'whos#who_starter_btn'
  get 'who/import_page' => 'whos#import_page'
  get 'who/search' => 'whos#search'
  get 'who_power_btn' => 'whos#who_power_btn'
  
  resources :indexer_terms do
    collection { post :import_csv_data }
  end
  get 'indexer_term/import_page' => 'indexer_terms#import_page'

  resources :indexers do
    collection {post :import_csv_data}
    #   get :merge_data, on: :collection
  end
  get 'indexer/search' => 'indexers#search'
  get 'indexer/import_page' => 'indexers#import_page'
  get 'page_finder_btn' => 'indexers#page_finder_btn'
  get 'reset_errors_btn' => 'indexers#reset_errors_btn'
  get 'indexer_power_btn' => 'indexers#indexer_power_btn'
  get 'template_finder_btn' => 'indexers#template_finder_btn'
  get 'rooftop_data_getter_btn' => 'indexers#rooftop_data_getter_btn'
  get 'meta_scraper_btn' => 'indexers#meta_scraper_btn'
  get 'indexer/show_detail' => 'indexers#show_detail'
  get 'url_redirect_checker_btn' => 'indexers#url_redirect_checker_btn'
  get 'score_calculator_btn' => 'indexers#score_calculator_btn'
  get 'scraper_migrator_btn' => 'indexers#scraper_migrator_btn'

  get 'migrate_address_to_staffers_btn' => 'indexers#migrate_address_to_staffers_btn'

  get 'id_sorter_btn' => 'indexers#id_sorter_btn'
  get 'finalizer_btn' => 'indexers#finalizer_btn'
  get 'phone_formatter_finalizer_btn' => 'indexers#phone_formatter_finalizer_btn'
  get 'geo_to_indexer_btn' => 'indexers#geo_to_indexer_btn'
  get 'address_formatter_btn' => 'indexers#address_formatter_btn'
  get 'phone_migrator_btn' => 'indexers#phone_migrator_btn'


  resources :locations do
    collection {post :import_csv_data}
    get :merge_data, on: :collection
    get :flag_data, on: :collection
  end
  get 'location/import_page' => 'locations#import_page'
  get 'location/search' => 'locations#search'
  get 'geo_places_starter_btn' => 'locations#geo_places_starter_btn'
  get 'location_power_btn' => 'locations#location_power_btn'
  get 'turbo_matcher_btn' => 'locations#turbo_matcher_btn'
  get 'location_cleaner_btn' => 'locations#location_cleaner_btn'
  get 'geo_update_migrate_btn' => 'locations#geo_update_migrate_btn'
  # get 'geo_starter_btn' => 'locations#geo_starter_btn'

  resources :staffers do
    collection { post :import_csv_data }
  end
  get 'staffer/import_page' => 'staffers#import_page'
  get 'staffer/search' => 'staffers#search'
  get 'staffer/acct_contacts' => 'staffers#acct_contacts'
  get 'cs_data_getter_btn' => 'staffers#cs_data_getter_btn'
  get 'staffer_sfdc_id_cleaner_btn' => 'staffers#staffer_sfdc_id_cleaner_btn'
  get 'staffer_power_btn' => 'staffers#staffer_power_btn'
  get 'crm_staff_counter_btn' => 'staffers#crm_staff_counter_btn'

  resources :cores do
    collection { post :import_core_data }
    get :merge_data, on: :collection
    get :flag_data, on: :collection
    get :drop_data, on: :collection
  end
  get 'core/import_page' => 'cores#import_page'
  get 'core/search' => 'cores#search'
  # # Clean Data Buttons
  # get 'core_comp_cleaner_btn' => 'cores#core_comp_cleaner_btn'
  get 'core_power_btn' => 'cores#core_power_btn'
  get 'col_splitter_btn' => 'cores#col_splitter_btn'

  resources :in_host_pos do
    collection { post :import_csv_data }
  end
  get 'in_host_po/import_page' => 'in_host_pos#import_page'

  resources :dashboards do
    collection { post :import_csv_data }
  end
  get 'dashboard/import_page' => 'dashboards#import_page'
  get 'dashboard_mega_btn' => 'dashboards#dashboard_mega_btn'
  get 'cores_dash_btn' => 'dashboards#cores_dash_btn'
  get 'delayed_jobs_dash_btn' => 'dashboards#delayed_jobs_dash_btn'
  get 'franchise_dash_btn' => 'dashboards#franchise_dash_btn'
  get 'indexer_dash_btn' => 'dashboards#indexer_dash_btn'
  get 'geo_locations_dash_btn' => 'dashboards#geo_locations_dash_btn'
  get 'staffers_dash_btn' => 'dashboards#staffers_dash_btn'
  get 'users_dash_btn' => 'dashboards#users_dash_btn'
  get 'whos_dash_btn' => 'dashboards#whos_dash_btn'
  get 'summarize_data' => 'dashboards#summarize_data'
  get 'dashboard_power_btn' => 'dashboards#dashboard_power_btn'


  devise_for :users

  #==== Delayed_Jobs_Interface Starts=========
  # match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # #==== Search Pages Start=========
  post 'search_result_page_core' => 'search#search_result_core'
  post 'search_result_page_staffer' => 'search#search_result_staffer'
  post 'search_result_page_location' => 'search#search_result_location'
  post 'search_result_page_indexer' => 'search#search_result_indexer'
  post 'search_result_page_indexer' => 'search#search_result_indexer'


  get 'admin/index'
  get 'admin/starters'
  get 'admin/change_user_level' => 'admin#change_user_level'
  get 'admin/delete_user' => 'admin#delete_user'
  get 'admin/developer' => 'admin#developer'

  root 'welcome#index'


  # Hide all CRUD actions 2017.03.10 ==================================

  # # === Google API Route ===
  # get '/search' => 'search#index'

  # resources :in_text_pos do
  #     collection { post :import_csv_data }
  # end
  # get 'in_text_po/import_page' => 'in_text_pos#import_page'
end

app/controllers/indexers_controller.rb
class IndexersController < ApplicationController
  before_action :intermediate_and_up, only: [:index, :show]
  before_action :advanced_and_up, only: [:edit, :update]
  before_action :admin_only, only: [:new, :create, :destroy, :import_page, :import_csv_data, :indexer_power_btn, :reset_errors_btn, :page_finder_btn, :template_finder_btn, :rooftop_data_getter_btn, :meta_scraper_btn, :score_calculator_btn, :scraper_migrator_btn, :migrate_address_to_staffers_btn, :id_sorter_btn, :finalizer_btn, :phone_formatter_finalizer_btn, :geo_to_indexer_btn, :address_formatter_btn, :phone_migrator_btn]
  before_action :set_indexer, only: [:show, :edit, :update, :destroy]
  before_action :set_indexer_service, only: [:page_finder_btn, :reset_errors_btn, :indexer_power_btn, :template_finder_btn, :rooftop_data_getter_btn, :meta_scraper_btn, :url_redirect_checker_btn, :score_calculator_btn, :scraper_migrator_btn, :migrate_address_to_staffers_btn, :id_sorter_btn, :finalizer_btn, :phone_formatter_finalizer_btn, :geo_to_indexer_btn, :address_formatter_btn, :phone_migrator_btn]
  before_action :set_option_list, only: [:index, :search]


  # GET /indexers
  # GET /indexers.json
  def index

    @indexers = Indexer.all

    if params[:score100_check] == "true"
      @indexers = @indexers.where.not("score100 = '{}'")
    end
    if params[:score75_check] == "true"
      @indexers = @indexers.where.not("score75 = '{}'")
    end
    if params[:score50_check] == "true"
      @indexers = @indexers.where.not("score50 = '{}'")
    end
    if params[:score25_check] == "true"
      @indexers = @indexers.where.not("score25 = '{}'")
    end


    ## SET ORDER OF DISPLAYED DATA ##
    @indexers = @indexers.order(updated_at: :desc)

    @indexers_count = Indexer.count
    @selected_indexers_count = @indexers.count

    # CSV #
    indexers_csv = @indexers.order(:clean_url)
    respond_to do |format|
      format.html
      format.csv { render text: indexers_csv.to_csv }
    end

    # @indexers = @indexers.paginate(:page => params[:page], :per_page => 100)

    # WILL_PAGINATE #
    @indexers = @indexers.filter(filtering_params(params)).paginate(:page => params[:page], :per_page => 50)


    batch_status
  end

  # GET /indexers/1
  # GET /indexers/1.json
  def show
  end

  # GET /indexers/new
  def new
    @indexer = Indexer.new
  end

  def import_page
  end

  def import_csv_data
    file_name = params[:file]
    Indexer.import_csv(file_name, Indexer, "indexer_status")

    flash[:notice] = "CSV imported successfully."
    redirect_to admin_developer_path
  end

  def search
    @indexer_count = Indexer.count
    @stf_status_opts = Dashboard.find_by(db_name: "Indexer", col_name: "stf_status").item_list
    @loc_status_opts = Dashboard.find_by(db_name: "Indexer", col_name: "loc_status").item_list
  end



  # GET /indexers/1/edit
  def edit
  end


  # POST /indexers
  # POST /indexers.json
  def create
    @indexer = Indexer.new(indexer_params)

    respond_to do |format|
      if @indexer.save
        format.html { redirect_to @indexer, notice: 'Indexer was successfully created.' }
        format.json { render :show, status: :created, location: @indexer }
      else
        format.html { render :new }
        format.json { render json: @indexer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indexers/1
  # PATCH/PUT /indexers/1.json
  def update
    respond_to do |format|
      if @indexer.update(indexer_params)
        format.html { redirect_to @indexer, notice: 'Indexer was successfully updated.' }
        format.json { render :show, status: :ok, location: @indexer }
      else
        format.html { render :edit }
        format.json { render json: @indexer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indexers/1
  # DELETE /indexers/1.json
  def destroy
    @indexer.destroy
    respond_to do |format|
      format.html { redirect_to indexers_url, notice: 'Indexer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_detail
    @core = Core.find(params[:core])
    @indexers = Indexer.where(clean_url: @core.alt_url).where(archive: false)
  end




  ### =============== BUTTONS Start ===============

  def finalizer_btn
    # Step 1: ID Sorters (4 methods)
    # @service.delay.url_arr_mover
    # @service.delay.pin_arr_mover
    # @service.delay.acct_arr_mover
    # @service.delay.acct_squeezer_caller
    # @service.delay.ph_arr_mover_express
    @service.url_arr_mover
    @service.pin_arr_mover
    @service.acct_arr_mover
    @service.acct_squeezer_caller
    @service.ph_arr_mover_express

    # Step 2: Score Calculator (1 method)
    # @service.delay.score_calculator
    @service.score_calculator

    # Step 3: Scraper Migrator (1 method)
    # @service.delay.scraper_migrator
    @service.scraper_migrator
    @service.migrate_address_to_staffers #=> New Button

    redirect_to admin_developer_path
  end

  def score_calculator_btn
    @service.score_calculator
    # @service.delay.score_calculator
    redirect_to admin_developer_path
  end

  def scraper_migrator_btn
    @service.scraper_migrator
    # @service.delay.scraper_migrator
    redirect_to admin_developer_path
  end

  def migrate_address_to_staffers_btn #=> New Button
    @service.migrate_address_to_staffers
    # @service.delay.migrate_address_to_staffers
    redirect_to admin_developer_path
  end

  def id_sorter_btn
    # Step 1: ID Sorters (4 methods)
    # @service.delay.url_arr_mover
    # @service.delay.pin_arr_mover
    # @service.delay.acct_arr_mover
    # @service.delay.ph_arr_mover_express
    @service.url_arr_mover
    @service.pin_arr_mover
    @service.acct_arr_mover
    @service.ph_arr_mover_express
    redirect_to admin_developer_path
  end

  def phone_formatter_finalizer_btn
    # @service.delay.phone_formatter_finalizer_caller
    @service.phone_formatter_finalizer_caller
    redirect_to admin_developer_path
  end

  def geo_to_indexer_btn
    @service.geo_to_indexer_caller
    redirect_to admin_developer_path
  end

  def address_formatter_btn
    @service.address_formatter
    redirect_to admin_developer_path
  end

  def phone_migrator_btn
    @service.phone_migrator
    redirect_to admin_developer_path
  end


  def indexer_power_btn
    # @service.geo_to_indexer
    # @service.url_arr_extractor
    # @service.scraped_contacts_sts_checker
    # @service.count_contacts
    # @service.dup_url_cleaner
    # @service.delay.dup_url_cleaner
    # @service.staff_url_cleaner
    # @service.url_downcase
    # @service.delay.url_downcase
    # @service.hyrell_cleaner
    # @service.template_counter
    # @service.stafflink_express
    # @service.core_url_redirect

    # @service.indexer_duplicate_purger
    # @service.db_data_trimmer


    # @service.job_title_migrator

    # @service.m_zip_remover

    # @service.pin_acct_counter
    # @service.junk_cleaner

    # @service.redirect_url_migrator


    # @service.delay.ph_arr_mover_express

    # @service.delay.count_staff
    # @service.count_staff

    # @service.delay.count_staff
    # @service.count_staff

    # PHONE FORMATTER METHODS
    # @service.core_phone_norm
    # @service.staff_phone_formatter
    # @service.phones_arr_cleaner
    # @service.remove_invalid_phones

    # @service.acct_pin_gen_starter
    # @service.acct_pin_gen_helper
    # @service.acct_squeezer_caller
    # @service.delay.acct_squeezer_caller
    # @service.delay.compare_acct_downcase_tester

    # @service.scraper_migrator

    redirect_to admin_developer_path
  end

  def url_redirect_checker_btn
    @service.url_redirect_checker
    # @service.delay.url_redirect_checker
  end



  def reset_errors_btn
    # @service.reset_errors

    redirect_to admin_developer_path
  end


  def page_finder_btn
    @service.page_finder_starter
    # @service.delay.page_finder_starter
    #   @service.url_importer

    redirect_to admin_developer_path
  end

  def template_finder_btn
    #   @service.template_finder
    #   @service.delay.template_finder
    redirect_to admin_developer_path
  end


  def rooftop_data_getter_btn
    @service.rooftop_data_getter
    #   @service.delay.rooftop_data_getter

    redirect_to admin_developer_path
  end

  def meta_scraper_btn
    @service.meta_scraper
    # @service.delay.meta_scraper

    redirect_to admin_developer_path
  end



  ### =============== BUTTONS End ===============




  private
  # Use callbacks to share common setup or constraints between actions.
  def set_indexer
    @indexer = Indexer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def indexer_params
    params.require(:indexer).permit( raw_url, :redirect_status, :clean_url, :indexer_status, :staff_url, :staff_text, :location_url, :location_text, :template, :crm_id_arr, :loc_status, :stf_status, :contact_status, :contacts_link, :acct_name, :rt_sts, :cont_sts, :full_addr, :street, :city, :state, :zip, :phone, :phones, :acct_pin, :raw_street, :who_status, :geo_status, :contacts_count, :clean_url_crm_ids, :acct_pin_crm_id, :archive, :crm_acct_ids, :crm_ph_ids, :score100, :score75, :score50, :score25, :rejected_ids, :flagged_ids, :dropped_ids, :bug, :bug_note, :cop_type, :cop_franchises, :flagged_note)
  end


  def filtering_params(params)
    params.slice(:raw_url, :redirect_status, :clean_url, :indexer_status, :template, :loc_status, :stf_status, :contact_status, :acct_name, :rt_sts, :cont_sts, :full_addr, :street, :city, :state, :zip, :phone, :acct_pin, :who_status, :geo_status, :score100, :score75, :score50, :score25, :bug, :cop_type)
  end


  def set_indexer_service
    @service = IndexerService.new
  end


  def batch_status
    ids = params[:multi_checks]
    return if ids.nil?
    status = params[:selected_status]
    for id in ids
      indexer = Indexer.find(id)
      indexer.update_attribute(:indexer_status, status)
      flash[:notice] = "Successfully updated"

app/helpers/indexers_helper.rb
module IndexersHelper

  def indexer_indicator(crm, geo)
    unless (crm == nil || geo == nil) || (crm == "" || geo == "")
      return crm != geo ? "ind-green" : ""
    end
  end
  
  def match_sts_ind(input)
    if input
      return input == "Matched" ? "ind-green" : ""
    end
  end

  def link_core_staffers(sfdc_ids)
    htmls = []
    sfdc_ids.each do |sfdc_id|
      core = Core.find_by(sfdc_id: sfdc_id)
      html = <<-HTML
      #{link_to sfdc_id, staffer_acct_contacts_path(core: core), :target => "_blank", class: 'scr-score-badge'}
      HTML
      htmls << html
    end
    htmls.join(' ').html_safe
  end

  # def link_core_staffers_with_url(indexer)
  #     clean_url = indexer.clean_url
  #     core = Core.find_by(sfdc_clean_url: clean_url)
  #     link_name = indexer.contact_status ? indexer.contact_status : "No contact_status"
  #
  #     link = <<-HTML
  #         #{link_to link_name, staffer_acct_contacts_path(indexer: indexer), :target => "_blank"}
  #     HTML
  #
  #     count = <<-HTML
  #         <span class="badge" data-toggle="tooltip" data-placement="top" title="staff #">#{indexer.web_staff_count}</span>
  #     HTML
  #     (link + " " + count).html_safe
  # end


  # def link_core_staffers_with_url(indexer)
  ## Replaced by newer version below.
  #     clean_url = indexer.clean_url
  #     core = Core.find_by(sfdc_clean_url: clean_url)
  #     link_name = indexer.contact_status ? indexer.contact_status : "No contact_status"
  #
  #     link = <<-HTML
  #         #{link_to indexer.web_staff_count, staffer_acct_contacts_path(indexer: indexer), :target => "_blank"}
  #     HTML
  #
  #     (link).html_safe
  # end


  def link_core_staffers_with_url(indexer)
    ## Replaces older version above.
    clean_url = indexer.clean_url
    core = Core.find_by(sfdc_clean_url: clean_url)
    if indexer.web_staff_count > 0
      link = <<-HTML
      #{link_to indexer.web_staff_count, staffer_acct_contacts_path(indexer: indexer), :target => "_blank"}
      HTML
      (link).html_safe
    else
      link = indexer.contact_status
    end
  end




end

app/views/indexers/_buttons.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="pull-right">
      <% if advanced_and_up %>
      <%= link_to 'Download CSV', indexers_path(format: "csv"), class: 'btn btn-primary btn-xs' %>
      <% end %>
    </div>
  </div>
</div>

app/views/indexers/_filter.html.erb
<%= form_tag "/indexers", method: :get, class: 'form-inline'  do %>
<div class="new-search-container">

  <div class="row">
    <div class="col-md-1 new-search-left-col">
      <table class="table table-bordered table-hover text-nowrap new-search-table">
        <tr>
          <th colspan="2">Match Status</th>
        </tr>
        <tr>
          <td>100%</td>
          <td><%= check_box_tag 'score100_check', "true" %></td>
          <tr>
            <td>75%</td>
            <td><%= check_box_tag 'score75_check', "true" %></td>
          </tr>
          <tr>
            <td>50%</td>
            <td><%= check_box_tag 'score50_check', "true" %></td>
          </tr>
          <tr>
            <td>25%</td>
            <td><%= check_box_tag 'score25_check', "true" %></td>
          </tr>
        </table>
      </div>

      <div class="col-md-11 new-search-right-col">
        <div class="row">
          <div class="col-md-12">
            <table class="table table-bordered table-hover text-nowrap new-search-table">
              <tr>
                <!-- Scraper Status -->
                <th class="fa-md-gray">
                  <%= fa_icon "diamond lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "Recent Scraper Status" %>
                </th>

                <!-- Redirect Status -->
                <th class="fa-md-gray">
                  <%= fa_icon "location-arrow lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "URL Redirect Status" %>
                </th>

                <!-- WhoIs Status -->
                <th class="fa-md-gray">
                  <%= fa_icon "address-book lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "WhoIs Status" %>
                </th>

                <!-- Template Status -->
                <th class="fa-md-gray">
                  <%= fa_icon "file-text lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "Dealer Template Status" %>
                </th>

                <!-- RT Status -->
                <th class="fa-md-gray">
                  <%= fa_icon "building lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "RoofTop Scraper Status" %>
                </th>

                <!-- PF Staff -->
                <th class="fa-md-gray">
                  <%= fa_icon "users lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "Dealer Staff Page Status" %>
                </th>

                <!-- PF Locations -->
                <th class="fa-md-gray">
                  <%= fa_icon "sitemap lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "Dealer Locations Page Status" %>
                </th>

                <!-- Contact Status -->
                <th class="fa-md-gray">
                  <%= fa_icon "user-plus lg shadow", "data-toggle": "tooltip", "data-placement": "top", title: "Contact Scraper Status" %>
                </th>
                <!-- <th>COP Status</th> -->
              </tr>
              <tr>
                <td><%= select_tag :indexer_status, options_for_select(@indexer_status_opts), multiple: true, class: 'selectpicker form-control', title: "[]" %></td>
                <td><%= select_tag :redirect_status, options_for_select(@redirect_status_opts), multiple: true, class: 'selectpicker form-control', title: "[]" %></td>

                <td><%= select_tag :who_status, options_for_select(@who_status_opts), multiple: true, class: 'selectpicker form-control', title: "[]" %></td>

                <td><%= select_tag :template, options_for_select(@template_opts), multiple: true, class: 'selectpicker form-control', title: "[]" %></td>

                <td><%= select_tag :rt_sts, options_for_select(@rt_sts_opts), multiple: true, class: 'selectpicker form-control', title: "[]" %></td>

                <td><%= select_tag :stf_status, options_for_select(@stf_status_opts), multiple: true, class: 'selectpicker form-control', title: "[]" %></td>
                <td><%= select_tag :loc_status, options_for_select(@loc_status_opts), multiple: true, class: 'selectpicker form-control', title: "[]" %></td>

                <td><%= select_tag :contact_status, options_for_select(@contact_status_opts), multiple: true, class: 'selectpicker form-control', title: "[]" %></td>

                <!-- CoPilot -->
                <!-- TEMPORARILY LINKING TO REDIRECT STATUS -->
                <!-- <td><%#= select_tag :cop_type, options_for_select(@contact_status_opts), multiple: true, class: 'selectpicker form-control', title: "[]" %></td> -->
              </tr>
            </table>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <table class="table table-bordered table-hover text-nowrap new-search-table">
              <tr>
                <th class="th">Account</th>
                <th class="th-2">Street</th>
                <th class="th-2">City</th>
                <th class="th-2">State</th>
                <th class="th-2">Zip</th>
                <th class="th-2">Full Address</th>
                <th class="th-2">Website</th>
                <th class="th-2">Phone</th>
              </tr>
              <tr>
                <td><%= render partial: 'layouts/text_field_tag', locals: { col: :acct_name } %></td>
                <td><%= render partial: 'layouts/text_field_tag', locals: { col: :street } %></td>
                <td><%= render partial: 'layouts/text_field_tag', locals: { col: :city } %></td>
                <td><%= select_tag :state, options_for_select(@state_opts), multiple: true, class: 'selectpicker form-control', title: "[]" %></td>
                <td><%= render partial: 'layouts/text_field_tag', locals: { col: :zip } %></td>
                <td><%= render partial: 'layouts/text_field_tag', locals: { col: :full_addr } %></td>
                <td><%= render partial: 'layouts/text_field_tag', locals: { col: :clean_url } %></td>
                <td><%= render partial: 'layouts/text_field_tag', locals: { col: :phone } %></td>
              </tr>
            </table>
          </div>
        </div>  <!-- row ends -->

      </div>
    </div>

  </div>

  <div class="row">
    <div class="col-md-3 scr-btn-1 text-center">
      <% if advanced_and_up %>
      <%= link_to 'Download CSV', indexers_path(format: "csv"), class: 'btn btn-primary btn-xs' %>
      <% end %>
    </div>

    <div class="col-md-6">
      <%= submit_tag "Search Scraper Results", class: 'new-wide-button' %>
    </div>

    <div class="col-md-3 text-center">
      <h5 class="inlined">Selected: <%= number_with_delimiter(@selected_indexers_count) %> | <%= number_with_delimiter(@indexer_count) %></h5>
    </div>

  </div>

  <% end %>

app/views/indexers/edit.html.erb
<h1>Editing Indexer</h1>

<%= render 'form', indexer: @indexer %>

<%= link_to 'Show', @indexer %> |
<%= link_to 'Back', indexers_path %>

app/views/indexers/import_page.html.erb
<h1>Import a CSV File</h1>

<div class="row">

  <div class="col-md-4">
    <p>Guidelines for CSV file</p>
    <ul>
      <li>Point 1.</li>
      <li>Point 1.</li>
      <li>Point 1.</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= form_tag import_csv_data_indexers_path, multipart: true do %>

    <div class="form-group">
      <%= file_field_tag :file, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= submit_tag "Import CSV", class: 'btn btn-success' %>
    </div>

    <% end %>
  </div>
</div>

app/views/indexers/index.html.erb
<!-- MODAL PARTIAL -->
<%= render partial: 'modal' %>

<!-- FILTER PARTIAL -->
<%= render partial: 'filter' %>


<% num = 0 %>
<% @indexers.each do |indexer| %>
<% num +=1 %>
<%= render partial: 'indexer_detail', locals: {indexer: indexer, num: num} %>
<% end %>


<div class="text-center">
  <%= will_paginate @indexers, renderer: BootstrapPagination::Rails  %>
</div>

app/views/indexers/new.html.erb
<h1>New Indexer</h1>

<%= render 'form', indexer: @indexer %>

<%= link_to 'Back', indexers_path %>

app/views/indexers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Raw url:</strong>
  <%= @indexer.raw_url %>
</p>

<p>
  <strong>Redirect status:</strong>
  <%= @indexer.redirect_status %>
</p>

<p>
  <strong>Clean url:</strong>
  <%= @indexer.clean_url %>
</p>

<p>
  <strong>Indexer status:</strong>
  <%= @indexer.indexer_status %>
</p>

<p>
  <strong>Staff url:</strong>
  <%= @indexer.staff_url %>
</p>

<p>
  <strong>Staff text:</strong>
  <%= @indexer.staff_text %>
</p>

<p>
  <strong>Location url:</strong>
  <%= @indexer.location_url %>
</p>

<p>
  <strong>Location text:</strong>
  <%= @indexer.location_text %>
</p>

<p>
  <strong>Template:</strong>
  <%= @indexer.template %>
</p>

<p>
  <strong>Crm id arr:</strong>
  <%= @indexer.crm_id_arr %>
</p>

<%= link_to 'Edit', edit_indexer_path(@indexer) %> |
<%= link_to 'Back', indexers_path %>